# Generated by Django 4.1.2 on 2022-11-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrate',
            name='order_number',
        ),
    ]
